
Sales Performance
#1. Total Sales Calculation: What is the total sales revenue generated by each sales representative? Provide a breakdown by month.
SELECT sales_rep, 
       months, 
       SUM(quantity * unit_price) AS total_sales_revenue
FROM sales_data
GROUP BY sales_rep, months
ORDER BY months

2. Profit Analysis: Which sales representative achieved the highest profit in a given year? What factors contributed to their success?
WITH ranked_data AS (
SELECT sales_rep,
      MAX(PROFIT) AS highest_profit,
      years,
      region,
      brands,
      count(sales_id) AS total_sales,
      sum(quantity) AS total_sales_volume,
      RANK() OVER (partition BY years ORDER BY MAX(profit) DESC) AS rank
FROM sales_data
GROUP BY years, sales_rep, region, brands
)
SELECT sales_rep, 
       highest_profit,
       years,
       brands,
       total_sales,
       total_sales_volume
FROM ranked_data
WHERE RANK = 1;

3. Cost vs. Revenue: For each country, calculate the profit margin (profit as a percentage of total cost) and identify which country has the highest margin.
SELECT countries, 
       (CAST(SUM(profit) AS FLOAT) / SUM(cost)) * 100 AS profit_margin
FROM sales_data
WHERE cost > 0
GROUP BY countries
ORDER BY profit_margin DESC;

4. Sales Trends Over Time: Analyze the trend of sales over the years. Are there any noticeable patterns or seasonal effects?
SELECT years,  SUM(unit_price * quantity) AS total_sales
  FROM sales_data
  GROUP BY years
  ORDER BY years DESC

5. Brand Performance: Which brand generated the highest revenue in the last year? How does this compare to previous years?
WITH ranked_brands AS (
    SELECT years,
           brands,
           SUM(unit_price * quantity) AS total_revenue,
           RANK() OVER (PARTITION BY years ORDER BY SUM(unit_price * quantity) DESC) AS rank_per_year
    FROM sales_data
    GROUP BY years, brands
)
SELECT *
FROM ranked_brands
WHERE rank_per_year = 1;

WITH ranked_brands AS (
    SELECT years,
           brands,
           SUM(unit_price * quantity) AS total_revenue,
           RANK() OVER (PARTITION BY years ORDER BY SUM(unit_price * quantity) DESC) AS rank_per_year
    FROM sales_data
    WHERE years IN (2018, 2019)
    GROUP BY years, brands
)
SELECT *
FROM ranked_brands
WHERE rank_per_year = 1;


 Market Insights
6. Regional Comparison: Compare sales performance across different regions. Which region has the highest total sales, and what might explain these differences?
SELECT region,
       sum(cost) as total_sales,
       sum(profit) as profit
  FROM sales_data
GROUP BY region
ORDER BY total_sales DESC;

8. Sales by Plant Cost: How does plant cost affect unit price and profit? Create a visual representation of this relationship.
SELECT plant_cost,
       unit_price,
       profit
 FROM sales_data

9. Top Selling Products: Identify the top three products (brands) sold in each country. What trends can be observed in product popularity?
WITH ranked_sales AS (
SELECT brands,
       countries,
       SUM(quantity) AS total_quantity,
RANK() OVER (PARTITION BY countries ORDER BY SUM(quantity) DESC )
FROM sales_data
GROUP BY brands, countries
)
SELECT 
       brands,
       countries,
       total_quantity
FROM ranked_sales
WHERE rank <= 3
ORDER BY countries, rank


10. Quantity Sold Analysis: What is the average quantity sold per transaction for each brand? Which brand has the highest average quantity sold?
SELECT 
      brands,
     CEIL(AVG(quantity)) AS average_quantity
FROM sales_data
GROUP BY brands
ORDER BY average_quantity DESC

12. Cost Control Analysis: Identify which countries have the highest average costs and investigate potential reasons for these high costs.
SELECT countries,
      ROUND(AVG(plant_cost),2) AS average_cost,
      SUM(cost) AS Total_sales
FROM sales_data
GROUP BY countries
ORDER BY average_cost DESC

13. Sales Rep Performance: Rank sales representatives based on their profitability over the last three years. What characteristics do top performers share?
SELECT sales_rep
       SUM(profit)
       Years
  FROM sales_data   
   ( RANK() OVER partition ORDER BY years)
   GROUP BY sales_rep
14. Impact of Regions on Profitability: How does profitability vary across different regions? Are there regions where certain brands perform better?
SELECT 
    region,
    brands,
    SUM(Profit) AS profit
FROM sales_data
GROUP BY region, brands
ORDER BY region, profit;
